---

- hosts: webservers
  tasks:

   - name: Install forever

     npm: name=forever global=yes state=present

   - name: clone a git repository
     command: git clone https://github.com/anujdevopslearn/SonarQubeNodeJS

   - name: installing npm

     command: npm install

     args:

       chdir: ~/SonarQubeNodeJS

   - name: start nodejs app

     command: forever start /root/SonarQubeNodeJS/app/server.js
